---
- name: MyWebSql | download MyWebSql
  get_url: url=https://sourceforge.net/projects/mywebsql/files/stable/mywebsql-3.6.zip/download dest=/var/www/db mode=0755

- unarchive: src=/var/www/db/mywebsql-3.6.zip dest=/var/www/db

- name: MyWebSql | create subdomain virtual host file
  template: src=vhost.conf dest=/etc/apache2/sites-available/db.conf

- name: Apache2 | a2ensite db.{{ setup.domain }}
  command: a2ensite db
  args:
    creates: /etc/apache2/sites-enabled/db.conf
  notify:
    - restart apache