---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install php7
  sudo: yes
  apt: pkg=php7.0 state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{php.packages}}"
  when: php.packages is defined

- name: Create Log directories
  file: path=/var/log/php state=directory owner=root group=adm mode=0777

- name: Initialize empty php error.log
  file: path=/var/log/php/error.log state=touch owner=root group=adm mode=0777

- include: configure.yml