---

- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp='memory_limit ='
              line='memory_limit = {{ php.memory_limit }}'

- name: ensure upload_max_filesize is set in apache2 php.ini
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp='upload_max_filesize ='
              line='upload_max_filesize = {{ php.upload_max_filesize }}'

- name: ensure max_execution_time is set in apache2 php.ini
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp='max_execution_time ='
              line='max_execution_time = {{ php.max_execution_time }}'

- name: enabling opcache
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'

- name: set error_reporting mod
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp=';?error_reporting=\d'
              line='error_reporting = E_ALL | E_STRICT'

- name: set error_log location mod
  lineinfile: dest=/etc/php/7.0/apache2/php.ini
              regexp=';?error_reporting=\d'
              line='error_log = /var/log/php/error.log'
