---
- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: set memory limit in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='memory_limit ='
              line='memory_limit = {{ php.memory_limit }}'

- name: set upload_max_filesize in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='upload_max_filesize ='
              line='upload_max_filesize = {{ php.upload_max_filesize }}'

- name: ensure max_execution_time is set in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='max_execution_time ='
              line='max_execution_time = {{ php.max_execution_time }}'

- name: enabling opcache cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'

- name: set error_reporting cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp=';?error_reporting=\d'
              line='error_reporting = E_ALL | E_STRICT'

- name: set error_log location cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp=';?error_reporting=\d'
              line='error_log = /var/log/php/error.log'