---
- name: PHPmyAdmin | debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'
- name: PHPmyAdmin | debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql.mysql_root_password}}' vtype='password'
- name: PHPmyAdmin | debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql.mysql_root_password}}' vtype='password'
- name: PHPmyAdmin | debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: PHPmyAdmin | Install pma
  apt: pkg=phpmyadmin state=present

- name: PHPmyAdmin | create subdomain virtual host file
  template: src=vhost.conf dest=/etc/apache2/sites-available/db.conf

- name: Apache2 | a2ensite db.{{ setup.domain }}
  command: a2ensite db
  args:
    creates: /etc/apache2/sites-enabled/db.conf
  notify:
    - restart apache