- hosts: all
  vars:
    root_dir: "{{playbook_dir}}/../public/ansible_developer_recipes"
    deploy_user: "{{ansible_user_id}}"


  tasks:
    - name: install requirements
      local_action: command ansible-galaxy install -r requirements.yml --ignore-errors


  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted