---
configs:
  use: 'devbox'
  devbox:
    vm_ip: '192.168.178.99'
    vm_hostname: 'devbox'
    vm_url: 'local.dev'
    vm_name: 'devbox'
    db_name: 'dbname'
    db_user: 'dbuser'
    db_pass: 'password'
